# Generated by Django 5.1 on 2024-09-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_last_edit',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Products', to='catalog.category', verbose_name='Категория'),
        ),
    ]
